name: sandboxZoo
version: 1.0.0
summary: A sandbox zoo environment with some different animals
description: sbx environment
runner: Bicep
templatePath: main.bicep
parameters:


- id: "storageAccountName"
  name: "storageAccountName"
  description: "Name of the storage account"
  default: ""
  type: "string"
  required: true

- id: "enableHierarchicalNamespace"
  name: "enableHierarchicalNamespace"
  description: "Enable Hierarchical Namespace"
  default: "true"
  type: "boolean"
  allowed:
    - "true"
    - "false"
  required: false

- id: "createMode"
  name: "createMode"
  description: "Create Mode"
  default: "default"
  type: "string"
  allowed:
    - "default"
    - "recover"
  required: false
